version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fpswe
    environment:
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: host.docker.internal

      JWT_SECRET: ${JWT_SECRET}
      AES_KEY: ${AES_KEY}

      APP_URL: ${APP_URL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SENDER_NAME: ${SMTP_SENDER_NAME}
      SMTP_AUTH_EMAIL: ${SMTP_AUTH_EMAIL}
      SMTP_AUTH_PASSWORD: ${SMTP_AUTH_PASSWORD}

      CLIENT_KEY: ${CLIENT_KEY}
      SERVER_KEY: ${SERVER_KEY}
      IS_PROD: ${IS_PROD}

      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
    ports:
      - "8080:8080"